#!/bin/sh

set -euo pipefail

echo "🔍 Running subscription-service e2e tests..."
( 
  cd subscription-service
  npm run test-only:e2e
)

echo "🔍 Running payment-service e2e tests..."
(
  cd payment-service
  npm run test-only:e2e
)

echo "✅ Pre-commit checks passed."

